### ISSUE TITLE
Unable to install and use function-patch-and-transform with Crossplane 1.17 on EKS 1.30

### ISSUE THREAD

**Issue by yazidmissaoui** [crossplane-contrib/function-patch-and-transform#144]
I'm experiencing issues installing and using the function-patch-and-transform with Crossplane 1.17 on an EKS 1.30 cluster. Here are the details:
Environment:

Crossplane version: 1.17
Kubernetes version: EKS 1.30
Function version: function-patch-and-transform:v0.7.0 : [Link](https://marketplace.upbound.io/functions/crossplane-contrib/function-patch-and-transform/v0.7.0)

**Issue:**
When trying to use a Composition that includes the function-patch-and-transform, I'm getting the following error:

`cannot compose resources: cannot run Composition pipeline step "patch-and-transform": cannot get gRPC client connection for Function "upbound-function-patch-and-transform": cannot find an active FunctionRevision (a FunctionRevision with spec.desiredState: Active)`

**Steps to reproduce:**

Installed Crossplane 1.17 on EKS 1.30 cluster
Attempted to install function-patch-and-transform using the YAML from the [Upbound Marketplace](https://marketplace.upbound.io/functions/crossplane-contrib/function-patch-and-transform/v0.7.0)
Created a Composition using the function-patch-and-transform
Tried to apply the Composition

**Current state:**

FunctionRevisions appear to be healthy and active:
```
kubectl get functionrevisions
CopyNAME                                        HEALTHY   REVISION   IMAGE                                                                    STATE    DEP-FOUND   DEP-INSTALLED   AGE
function-auto-ready-ad9454a37aa7            True      1          xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1            Active                               31m
function-patch-and-transform-6a1ab24d2512   True      1          xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.7.0   Active                               43m
```
However, no Functions are found:
```
kubectl get functions
No resources found
```

Expected behavior:
The Function should be installed successfully, and the Composition should be able to use it without errors.
Additional context:

The deployment for the function seems to be running correctly
I've verified that the necessary secrets and service accounts are in place

Any assistance in resolving this issue would be greatly appreciated. Let me know if you need any additional information.

**Comment by jbw976** [comment]
Could you try the fully qualified name for functions that includes the group? I wonder if `functions` is conflicting with another CRD type on your cluster and so it's showing 0:
```
kubectl get functions.pkg.crossplane.io
NAME                           INSTALLED   HEALTHY   PACKAGE                                                                  AGE
function-patch-and-transform   True        True      xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.7.0   71s
```

> cannot get gRPC client connection for Function "upbound-function-patch-and-transform"

I wonder if this is just the `functionRef` in your pipeline step isn't exactly matching the name the function is installed as.  Let's see what the fully qualified `kubectl get functions.pkg.crossplane.io` says from above and go from there... 🙏

**Comment by yazidmissaoui** [comment]
Yes, thank you, it is ok when i tried : 
`kubectl get functions.pkg.crossplane.io`
