### ISSUE TITLE
Make patch type required

### ISSUE THREAD

**Issue by negz** [crossplane-contrib/function-patch-and-transform#19]
See discussion at https://github.com/crossplane-contrib/function-patch-and-transform/pull/16#issuecomment-1743954496.

This would almost certainly make porting to `function-patch-and-transform` more of a pain for most folks, but it may be worth it to make P&T Compositions more explicit and readable in future.

**Comment by ytsarev** [comment]
In this case, the migration from the current Crosslane core P&T will be more than just indenting the yaml :) 
I believe it's ok, just needs to be documented somewhere explicitly.

**Comment by stevendborrelli** [comment]
This could be added to https://github.com/crossplane-contrib/crossplane-migrator in the same we we populate missing ConnectionSecret keys.

**Comment by stevendborrelli** [comment]
Added issue here https://github.com/crossplane-contrib/crossplane-migrator/issues/6

**Comment by negz** [comment]
I'm kind of feeling like the ship has sailed on this one. There's enough folks using this function now that we probably can't make such a breaking change easily. I feel okay leaving it as is - let me know if anyone disagrees.
