### ISSUE TITLE
Required fromFieldPath patch policy can cause incorrectly ready XRs and unintentional deletion of managed resources

### ISSUE THREAD

**Issue by JonathanO** [crossplane-contrib/function-patch-and-transform#70]
When the Required fromFieldPath patch policy is used a missing field causes the affected resource not to be rendered in the result from the function. Since the affected resource is not rendered crossplane will behave as if it does not exist. If the missing field is a result of updating a composition this will lead to existing managed resources being deleted. This is a change in behaviour from native patch and transform.

This is similar to #59, however that issue deals with genuine errors in the patch, which perhaps should be fatal, while making missing required fields fatal would probably be undesirable (since they may be the result of waiting on a ToCompositeFieldPath patch from the status of another resource.)

A simple test case is attached:
[testcase.zip](https://github.com/crossplane-contrib/function-patch-and-transform/files/13744115/testcase.zip)

Using native patch and transform the behaviour is either:
A) if the composite already contains the Required policy when you create the XR then the failing ManagedResource is repeatedly recreated, and the XR does not become ready.
B) if you are updating the composite to add the Required policy then the existing MR remains in place, and the XR becomes not Synced. The external resource is not deleted.

With function-patch-and-transform the behaviour is that the resource is not rendered, the XR is Ready and Synced, and any existing MR (in case B) is deleted. A warning is logged as an event to the XR, but this does not affect the XR status.

**Comment by JonathanO** [comment]
Possible solutions:

A) Make a missing Required field fatal. This would mean they can no longer be used to read from status fields populated by patching from status of other MRs in the composite: None of the resources returned by the function would be applied, so it would never eventually converge.

B) Keep the current behaviour, make it a normal result rather than a warning, and update the docs. This means Required fields could be used to intentionally prevent rendering of some resources if certain fields are omitted from the spec. Perhaps also limit use of Required to only fromFields in metadata and spec to avoid confusion.

C) Allow functions to return a list of resources which failed to render, and use that to reimplement behaviour similar to what happens with native patch and transform.

I would like to see option C, but it looks like it requires a change to crossplane's composition function interface.

**Comment by negz** [comment]
What does it mean for a required patch of (to) an existing resource to fail?

It's been a while so I just skimmed https://github.com/crossplane/crossplane/issues/2094 to refresh my memory. As far as I recall, the intention of a required field path was to block the creation of composed resources until the patch could succeed. Per https://github.com/crossplane/crossplane/pull/2133:

> This can be used to block the creation of a composed resource until the field path exists on the composite resource.

I'm wondering if it would make sense to only honor required field paths for resources that don't exist yet. That is, if:

* A patch was from a required field path.
* The patch was to a resource that already exists.
* The required field path did not exist.

We'd handle the patch the same way we would handle a missing optional field path - skip that specific patch but process all the others. Maybe also emit a warning result noting that we skipped the patch.

**Comment by negz** [comment]
Elaborating on my previous comment, I think we'd have the following cases:

|Patch|Field Path Policy|Result|
|-|-|-|
|XR -> New composed resource |Required|Emit an event. Don't create the composed resource.|
|XR -> New composed resource|Optional|Skip the patch. Create the composed resource.|
|XR -> Existing composed resource |Required|Emit an event. Skip the patch.|
|XR -> Existing composed resource|Optional|Skip the patch.|
|All other patches|Required|Emit an event. Skip the patch.|
|All other patches|Optional|Skip the patch.|

All other patches are patching to something that already exists, i.e.:

* Composed resource -> XR
* Composed resource -> Environment
* XR -> Environment
* Environment -> XR
