### ISSUE TITLE
Merge options

### ISSUE THREAD

**Issue by christopherparo** [crossplane-contrib/function-patch-and-transform#75]
Are there plans to add support for this similar to what is in the original p/t feature?

https://docs.crossplane.io/latest/concepts/patch-and-transform/#merge-options

Apologies if this is already supported and I missed it somewhere.

**Comment by negz** [comment]
I'm hoping we can avoid it.

Functions use [server side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) (SSA) to apply their desired state. SSA is supposed to be able to handle merging arrays and objects correctly. The only catch is that the [merge strategy](https://kubernetes.io/docs/reference/using-api/server-side-apply/#merge-strategy) needs to be configured for each type of custom resource (e.g. for each Crossplane MR) at the schema level. We've made some progress toward that per https://github.com/crossplane/upjet/issues/300.

**Comment by christopherparo** [comment]
Oh this is perfect! Thank you. Closing
